# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Envnest < Formula
  desc "Secure environment variable management for teams and CI/CD."
  homepage "https://github.com/envnest/envnest-cli"
  version "0.1.0-rc.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://dl.envnest.dev/cli/v0.1.0-rc.5/envnest_0.1.0-rc.5_darwin_amd64.tar.gz"
      sha256 "c16b951fa14056f226041b489cf47caa8ddef98acf13d2d218a1d70bedec905d"

      def install
        bin.install "envnest"
      end
    end
    if Hardware::CPU.arm?
      url "https://dl.envnest.dev/cli/v0.1.0-rc.5/envnest_0.1.0-rc.5_darwin_arm64.tar.gz"
      sha256 "d0c736dae0dd57432e7584abb3657438e0a4f89c0706055926e3daff3c0f3d8a"

      def install
        bin.install "envnest"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://dl.envnest.dev/cli/v0.1.0-rc.5/envnest_0.1.0-rc.5_linux_amd64.tar.gz"
      sha256 "0a334e868924e7a344533557168208d218d9e71c0f9c42b072ec931738093827"
      def install
        bin.install "envnest"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://dl.envnest.dev/cli/v0.1.0-rc.5/envnest_0.1.0-rc.5_linux_arm64.tar.gz"
      sha256 "3b84a3d404b3bde66a8ea11a8be374891c5eac1043aaef79eb262aaf6082f318"
      def install
        bin.install "envnest"
      end
    end
  end
end
