# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Envnest < Formula
  desc "Secure environment variable management for teams and CI/CD."
  homepage "https://github.com/envnest/envnest-cli"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/envnest/envnest-cli/releases/download/v0.1.0/envnest_0.1.0_darwin_amd64.tar.gz"
      sha256 "1ab31a436c934ee1f79a4bd2cf54a6c5533d88e16d0f421c473817d5ed5c97a3"

      def install
        bin.install "envnest"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/envnest/envnest-cli/releases/download/v0.1.0/envnest_0.1.0_darwin_arm64.tar.gz"
      sha256 "aca5ae5cbf291b05e5a88e3777b1d4005053deea89124fe6018233de67c86e74"

      def install
        bin.install "envnest"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/envnest/envnest-cli/releases/download/v0.1.0/envnest_0.1.0_linux_amd64.tar.gz"
      sha256 "25c50afdf22b0a5a2fc618432e4debb11371812f5aba5576da103d66ac3950fa"
      def install
        bin.install "envnest"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/envnest/envnest-cli/releases/download/v0.1.0/envnest_0.1.0_linux_arm64.tar.gz"
      sha256 "54339d0256b7da8fe197b6a5d71e6dd91ef68263d671808eae185bca41715061"
      def install
        bin.install "envnest"
      end
    end
  end
end
