# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Envnest < Formula
  desc "Secure environment variable management for teams and CI/CD."
  homepage "https://github.com/envnest/envnest-cli"
  version "0.1.0-rc.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/envnest/envnest-cli/releases/download/v0.1.0-rc.1/envnest_0.1.0-rc.1_darwin_amd64.tar.gz"
      sha256 "5a53192c807dc083990ae19d160b0df3c16f4523cf1e47e986ad568a660a2e3a"

      def install
        bin.install "envnest"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/envnest/envnest-cli/releases/download/v0.1.0-rc.1/envnest_0.1.0-rc.1_darwin_arm64.tar.gz"
      sha256 "e4e48038b109d198268532e047b47761a2af8a99904b675b67572c1ff0ca7c0e"

      def install
        bin.install "envnest"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/envnest/envnest-cli/releases/download/v0.1.0-rc.1/envnest_0.1.0-rc.1_linux_amd64.tar.gz"
      sha256 "f609853126666c5716db6649a6a5ad465e8910efe49639a427d2822363ac7779"
      def install
        bin.install "envnest"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/envnest/envnest-cli/releases/download/v0.1.0-rc.1/envnest_0.1.0-rc.1_linux_arm64.tar.gz"
      sha256 "79f3d64471d0386a4fe9ec097b260f78f2a4dd14115a933c9f702048e4db9573"
      def install
        bin.install "envnest"
      end
    end
  end
end
