# This file was generated by GoReleaser. DO NOT EDIT.
cask "envnest" do
  name "envnest"
  desc "Secure environment variable management for teams and CI/CD."
  homepage "https://github.com/envnest/envnest-cli"
  version "0.1.0-rc.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "envnest"

  on_macos do
    on_intel do
      url "https://dl.envnest.com/cli/v#{version}/envnest_#{version}_darwin_amd64.tar.gz"
      sha256 "5ba8d5278c1745204cdd6185f7403a9e73bb24f31504f5dda983bf5e2db251c9"
    end
    on_arm do
      url "https://dl.envnest.com/cli/v#{version}/envnest_#{version}_darwin_arm64.tar.gz"
      sha256 "874c032aa0f75c40507ed5a50d32a982a366519896f3a77e69f821793657e1de"
    end
  end

  on_linux do
    on_intel do
      url "https://dl.envnest.com/cli/v#{version}/envnest_#{version}_linux_amd64.tar.gz"
      sha256 "c6bca2c228db7a20c11fe550eed26f3fbeed0b9cdca86f5bca47e34737ccb836"
    end
    on_arm do
      url "https://dl.envnest.com/cli/v#{version}/envnest_#{version}_linux_arm64.tar.gz"
      sha256 "f82eab2957363cd930dd6bafd95adabe9d7f211567d29a30eb2f815eef568e47"
    end
  end

  # No zap stanza required
end
