# This file was generated by GoReleaser. DO NOT EDIT.
cask "envnest" do
  name "envnest"
  desc "Secure environment variable management for teams and CI/CD."
  homepage "https://github.com/envnest/envnest-cli"
  version "0.1.0-rc.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "envnest"

  on_macos do
    on_intel do
      url "https://dl.envnest.dev/cli/v#{version}/envnest_#{version}_darwin_amd64.tar.gz"
      sha256 "028adfba4d5113d59184ed2ad45b51b86ad163b346ee7cb7fcd35f07a4b3f7b5"
    end
    on_arm do
      url "https://dl.envnest.dev/cli/v#{version}/envnest_#{version}_darwin_arm64.tar.gz"
      sha256 "b92db62333b7dc452d13ae0cf0be0b1aec190b7ef73244513c761620133f54fc"
    end
  end

  on_linux do
    on_intel do
      url "https://dl.envnest.dev/cli/v#{version}/envnest_#{version}_linux_amd64.tar.gz"
      sha256 "e4de99b2b98e56c9ae1ecdde48c8038d706c2a6ebcf0d14f01158d29770e6aa1"
    end
    on_arm do
      url "https://dl.envnest.dev/cli/v#{version}/envnest_#{version}_linux_arm64.tar.gz"
      sha256 "1059a37e47beffb0cff90a72e9d4ad29b1b7af9958a24fd6b1e55376ff5aba13"
    end
  end

  # No zap stanza required
end
