# This file was generated by GoReleaser. DO NOT EDIT.
cask "envnest" do
  name "envnest"
  desc "Secure environment variable management for teams and CI/CD."
  homepage "https://github.com/envnest/envnest-cli"
  version "0.1.0-rc.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "envnest"

  on_macos do
    on_intel do
      url "https://github.com/envnest/envnest-cli/releases/download/v#{version}/envnest_#{version}_darwin_amd64.tar.gz"
      sha256 "a7bdb3b9018a49e23a6d7c6d54ed7550833fe3b8ff273aef0311234415f8bdea"
    end
    on_arm do
      url "https://github.com/envnest/envnest-cli/releases/download/v#{version}/envnest_#{version}_darwin_arm64.tar.gz"
      sha256 "fe028647af8ce2a769a8d0b1d02442e6fc5aec331b7322476e694ba3eb201ef3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/envnest/envnest-cli/releases/download/v#{version}/envnest_#{version}_linux_amd64.tar.gz"
      sha256 "67b75f3111c90e863faaf9dab9669c96809494308ca1fd940700b71bff6f95db"
    end
    on_arm do
      url "https://github.com/envnest/envnest-cli/releases/download/v#{version}/envnest_#{version}_linux_arm64.tar.gz"
      sha256 "c9004ec98e6f781ecc7a81ec5ba5e8749ba4cbe180ab2216ae39522055bc1a2f"
    end
  end

  # No zap stanza required
end
